name: React CI

on:
  push:
    branches:
      - develop
      - FE-2-add-dockerfile
      - FE-3-add-common-pages
      - FE-4-implement-transition
      - FE-5-add-state-manager
      - FE-6-add-axios
      - main
  pull_request:
    branches:
      - develop
      - FE-2-add-dockerfile
      - FE-3-add-common-pages
      - FE-4-implement-transition
      - FE-5-add-state-manager
      - Fe-6-add-axios
      - main
env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build project
        run: npm run build
